def word_counter(text):
    # Remove punctuation and split the text into words
    words = text.split()
    word_count = len(words)
    return word_count

# Example usage
input_text = "1) The use of CAFO's does indeed compromise Ben and Jerry's mission of \"innovating to make the world a better place\". It does this by placing profits over the lives of sentient beings, in this case cows, in order to acquire the milk needed to make the ice cream people enjoy everyday. It violates the social mission by resorting to traditional and modern animal abuse practice which not only lacks innovation but is cruel to the animals. This practice also violates their Economic mission by \"contribut[ing] significantly to pollution because they release heavy-concentrations of animal waste into the ground, water sources and air.\" Polluting our environemnt for the sake of profit is not sustainable financial growth. They need to put the environment over profit for long term financial growth or there will be no more usable land and cows to produce the milk needed for their operations. Organic and free-range alternatives offer a way for them to acquire their milk without harming the environment and I feel that if they do not shift to more sustainable practices they will continue to violate their mission. 2) I beleive that the growth of Ben & Jerry's has contributed to the greenwashing of the company. Greenwashing is the practice of promoting the company as environmentally friendly while actually contribuiting to practices that are harmful to the environment. By engaging in CAFO they are in stark opposition to the environmentally friendly brand image they want to convey. Unilever on the whole has been met by critics over its environemental impact. Using Ben & Jerry\'s image to greenwash their brand is a slimy tactic. Ben and Jerry\'s promotes grass roots activism while Unilever is the large parent comapny focused on deriving profits from their endeavours. I think that Unilever actually lacks a commitment to sustainability and is using Ben and Jerry\'s as a greenwashing vehicle to entice customers and achieve higher profit margins. "
count = word_counter(input_text)
print(f"Word Count: {count}")
